# Generated by Django 4.2.4 on 2023-09-02 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CuidadorMascotas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('biografia', models.TextField()),
                ('entrenamiento_cuidado_perros', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DuenoMascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('canino', 'Canino'), ('felino', 'Felino')], max_length=10)),
                ('raza', models.CharField(max_length=50)),
                ('edad', models.PositiveIntegerField()),
                ('dueno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MVP.duenomascota')),
            ],
        ),
    ]
